name: DemoDeploy

on:
  push:
    branches: [dev]

jobs:
  demo-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Demo Install
        run: npm install
        working-directory: demo

      - name: Demo Build
        run: npm run build
        working-directory: demo

      # Deploy Demo
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: demo/build # The folder the action should deploy.